## This data has been generated by the MaP (Marseille Proteomics)
## this data illustrate perfectly the batch effect; MSstatsTMT appears to be a really good solution for removing this batch effect
## because of the normalization done after the quantification process of the package
## You can retake this data to test the app or the functions from the package and of course in the MSstatsTMT package

## The data contains two batch ('blue', 'red'), there is for controls, four patient in each batch (SKI and TTC),
## and two heterozygotes (ctrlHB and ctrlHR, thay have the gene but are not sick)
## There is ten channels in each batch (the controls are the same in the two batch)

#the base data are from the MaxQuant output, so need proteinGroups and evidence file
mqpar25_prgrp <- read.table("data-raw/proteinGroups.txt", sep = "\t",
                            header = TRUE)

mqpar25_evidence <- read.table("data-raw/evidence.txt", sep = "\t",
                               header = TRUE)


### The annotation file
ANNO <- data.frame(matrix(ncol = 7, nrow = length(unique(mqpar25_evidence$Raw.file)[order(unique(mqpar25_evidence$Raw.file))]
)*10
))

colnames(ANNO) <- c("Run", "Fraction", "TechRepMixture", "Channel",
                    "Condition", "Mixture", "BioReplicate")

Run <- unique(mqpar25_evidence$Raw.file)[order(unique(mqpar25_evidence$Raw.file))]
Run <- Run[order(nchar(Run), Run)]
Run <- rep(Run, each = 10)
ANNO$Run <- Run

Fraction <- c(1:14)
Fraction <- rep(Fraction, each = 10)
Fraction <- rep(Fraction, 2)
Fraction <- as.character(Fraction)
ANNO$Fraction <- Fraction

channel <- paste("channel.", c(1:10), sep = "")
channel <- rep(channel, 28)
channel <- as.factor(channel)
ANNO$Channel <- channel

techrep <- rep(1,each = length(levels(channel)))
techrep <- rep(techrep, nrow(ANNO)/length(techrep))
techrep <- as.character(techrep)
ANNO$TechRepMixture <- techrep

cond <- c("Norm", "M") #mettre un matrix input avec correspondance channel
cond <- rep(cond, 4)
cond <- append(cond, c("ctrlH", "ctrlH"))
cond <-  rep(cond, nrow(ANNO)/length(levels(channel)))
cond <- as.factor(cond)
ANNO$Condition <- cond

batch <- c("Bleu", "Rouge")
batch <- rep(batch, each = nrow(ANNO)/length(batch))
batch <- as.factor(batch)
ANNO$Mixture <- batch

ANNO$BioReplicate <- paste(ANNO$Mixture, "_", ANNO$Condition, sep = "")

mqpar25_annotation <- ANNO



### save the results from MSsatsTMT package
mqpar25_MSstat <- MaxQtoMSstatsTMTFormat(mqpar25_evidence, mqpar25_prgrp, mqpar25_annotation)


quant_mqpar25 <- proteinSummarization(mqpar25_MSstat,
                                      method = "msstats", #method of summarization (msstats include imputation at peptide level)
                                      global_norm = TRUE, #median normalization on peptide level before protein level
                                      reference_norm = TRUE, #reference channel based norma, annotated by Norm in condition
                                      remove_norm_channel = FALSE, #don't remove the ctrl channel
                                      remove_empty_channel = TRUE,
                                      MBimpute = TRUE) #remove empty channel

mqpar25_pairwise <- groupComparisonTMT(quant_mqpar25, remove_norm_channel = FALSE,
                                       remove_empty_channel = TRUE,
                                       adj.method = "none")



usethis::use_data(mqpar25_evidence, overwrite = TRUE)
usethis::use_data(mqpar25_prgrp, overwrite = TRUE)
usethis::use_data(mqpar25_annotation, overwrite = TRUE)
usethis::use_data(mqpar25_MSstat, overwrite = TRUE)
usethis::use_data(quant_mqpar25, overwrite = TRUE)
usethis::use_data(mqpar25_pairwise, overwrite = TRUE)









